frontend_eslint:
  image: node:latest
  before_script:
   - cd ./Frontend
   - npm install
   - cd ..

  when: always
  script:
    - cd ./Frontend
    - npm run lint
    - cd ..

backend:
  image: python:alpine
  services:
    - name: bitnami/mongodb:latest
      alias: mongo

  variables:
    MONGO_HOST: mongo
    MONGODB_DATABASE: pvk_test
    MONGODB_USERNAME: pvk_user
    MONGODB_PASSWORD: pvk_pass

  before_script:
   - pip install tox
  script:
    - cd ./Backend
    - tox
    - cd ..

